name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI Pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Env_module/Pre_prod

    steps:
      #-----------------------------------------
      # Checkout Repository
      #-----------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      #-----------------------------------------
      # Setup Terraform
      #-----------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Version
        run: terraform version

      #-----------------------------------------
      # Terraform Formatting
      #-----------------------------------------
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      #-----------------------------------------
      # Terraform Initialization
      #-----------------------------------------
      - name: Terraform Init
        run: terraform init

      #-----------------------------------------
      # Setup TFLint
      #-----------------------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Check TFLint Version
        run: tflint --version

      - name: Run TFLint
        run: tflint

      #-----------------------------------------
      # Terraform Validation
      #-----------------------------------------
      - name: Terraform Validate
        run: terraform validate

      #-----------------------------------------
      # Checkov Security Scan
      #-----------------------------------------
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: Env_module/Pre_prod
          framework: terraform
          soft_fail: false

      #-----------------------------------------
      # Azure Login
      #-----------------------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #-----------------------------------------
      # Terraform Plan
      #-----------------------------------------
      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        run: terraform plan -input=false